# Generated by Django 5.2.8 on 2025-11-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_produto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
